### ISSUE TITLE
Erro encontrado

### ISSUE THREAD

**Issue by evssousa** [a-juliamoreira/PROJETO-2-SIMULANDO-UM-BLOG-COM-CLASSES#1]
```
node index.js
/home/runner/aulas/PROJETO-2-SIMULANDO-UM-BLOG-COM-CLASSES-main/Author.js:6
        this.post = post
                    ^

ReferenceError: post is not defined
    at new Author (/home/runner/aulas/PROJETO-2-SIMULANDO-UM-BLOG-COM-CLASSES-main/Author.js:6:21)
    at Object.<anonymous> (/home/runner/aulas/PROJETO-2-SIMULANDO-UM-BLOG-COM-CLASSES-main/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.2
```

**Comment by ajuliamoreira** [comment]
corrigido! por favor atualizar
